-
  hosts: host11
  become: true
  user: ubuntu
  gather_facts: false

  tasks:
    - name: add cumulus user
      ansible.builtin.user: 
        name: cumulus
        group: admin
        shell: /bin/bash
        comment: "admin user"
        password: "$6$alq$WRoBPYvpxl0kxnfgcCB6SZ1MxRmBV8/aHhwGAOn17fp8pszaAsVzxy7qPUBHX71ovin1epXCbleKgiUcqlrzT1"  
        
    - name: Creates directory
      file:
        path: /home/cumulus/.ssh
        state: directory
        owner: cumulus
        group: admin
        mode: 0640
  
    - name: ensure file exists
      copy:
        content: ""
        dest: /home/cumulus/.ssh/authoriced_keys.pub
        force: no
        group: admin
        owner: cumulus
        mode: 0640
    
