#!/bin/bash

# ALQ, Wittdün 2022
# 28.10.2022 
#   fixed typos
# run via $ sudo bash start

sudo ansible-playbook /home/ubuntu/ON-03/.main.yaml

# Wirklich kein best practice

USER="cumulus"
USERPASS="Academy123"
TARGET1="host11"
TARGET2="host22"

CUMULUS_HOME="/home/cumulus"
echo "cumulus_home :$CUMULUS_HOME"

KEYLOCATION="$CUMULUS_HOME/.ssh/authorized_keys"

# geht noch nicht wirklich oder es ist mal wieder zu spät zum denken...
#echo "$USERPASS" | sshpass ssh-copy-id -f -i /home/ubuntu/.ssh/id_rsa.pub "$USER"@"$TARGET1"
#echo "$USERPASS" | sshpass ssh-copy-id -f -i /home/ubuntu/.ssh/id_rsa.pub "$USER"@"$TARGET2"

ssh-copy-id cumulus@host11
ssh-copy-id cumulus@host22

echo "nach ssh-copy-id"

whoami
sudo -i -u cumulus bash << EOF
  echo "USER :$USER"
  echo "DIR  :$PWD"
  cd "$CUMULUS_HOME"
  echo "DIR :$PWD"
  
  echo "test ob ON-01 nicht existiert"

  if [ ! -d "$CUMULUS_HOME/ON-01" ]; then
    git clone https://github.com/laquiante/ON-01
    echo "git clone done"
  fi

  echo "test ob ON-01 existiert"

  if [ -d "$CUMULUS_HOME/ON-01" ]; then
    cd $CUMULUS_HOME/ON-01
    sudo chmod 744 $CUMULUS_HOME/ON-01/prepare
    export PATH="$CUMULUS_HOME/ON-01/:$PATH" 
    echo "calling /home/cumulus/ON-01/prepare"
    sudo bash "$CUMULUS_HOME/ON-01/prepare"
  fi

EOF

clear
echo "Please consider switching to user to cumulus"
echo "Please make sure/verify you end up in the target user directory"
exit 0 
