#!/bin/bash

# ALQ, Wittdün 2022
# run via $ sudo bash start

sudo ansible-playbook /home/ubuntu/ON-03/main.yaml

# Wirklich kein best practice

USER="cumulus"
USERPASS="Academy123"
TARGET1="host11"
TARGET2="host22"

CUMULUS_HOME="/home/cumulus"
echo "cumulus_home :$CUMULUS_HOME"

echo "$USERPASS" | sshpass ssh-copy-id -f -i $KEYLOCATION "$USER"@"$TARGET1"
echo "$USERPASS" | sshpass ssh-copy-id -f -i $KEYLOCATION "$USER"@"$TARGET2"

whoami
sudo -i -u cumulus bash << EOF
  echo "USER :$USER"
  echo "DIR  :$PWD"
  cd $CUMULUS_HOME"
  echo "DIR :$PWD"

  if [ ! -d "$CUMULUS_HOME/ON-01" ]; then
    git clone https://github.com/laquiante/ON-01
  fi


  if [ -d "$CUMULUS_HOME/ON-01" ]; then
    cd $CUMULUS_HOME/ON-01
    sudo chmod 744 $CUMULUS_HOME/ON-01/prepare
    export PATH="$CUMULUS_HOME/ON-01/:$PATH" 
    sudo bash "$CUMULUS_HOME/ON-01/prepare"
  fi

EOF

echo "Please consider switching to user to cumulus"

exit 0 
