#!/bin/bash

# ALQ, Wittdün 2022

sudo ansible-playbook /home/ubuntu/ON-03/main.yaml

# Wirklich kein best practice

USER="cumulus"
USERPASS="Academy123"
TARGET1="host11"
TARGET2="host22"

CUMULUS_HOME="/home/cumulus"

echo "$USERPASS" | sshpass ssh-copy-id -f -i $KEYLOCATION "$USER"@"$TARGET1"
echo "$USERPASS" | sshpass ssh-copy-id -f -i $KEYLOCATION "$USER"@"$TARGET2"

whoami
sudo -i -u cumulus bash << EOF
echo "In"
whoami
EOF
echo "Out"
whoami

echo "USER :$USER"
echo "DIR  :$PWD"
cd $CUMULUS_HOME
echo "DIR :$PWD"

git clone https://github.com/laquiante/ON-01
cd $CUMULUS_HOME
sudo chmod 744 ./prepare

export PATH="$CUMULUS_HOME/ON-01/:$PATH" 

sudo ./prepare

exit 0 
